global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "agileai-backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "agileai-backend:8000"
